version: '3'

services:

  redis:
    container_name: redis 
    image: mleinfelder/linuxtips-giropops-senhas-redis:1.0
    ports:
      - "6379:6379"

    
  flask:       
   container_name: giropops-senhas
   image: mleinfelder/linuxtips-giropops-senhas:1.0
   ports:
     - "5000:5000"
   depends_on:
     - redis
   environment:
      - REDIS_HOST=redis
